kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # https://github.com/kubernetes-sigs/kind/releases
  - role: control-plane
    image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
  - role: worker
    image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 32012
        hostPort: 32012
        protocol: TCP
      - containerPort: 32022
        hostPort: 32022
        protocol: TCP
      - containerPort: 32032
        hostPort: 32032
        protocol: TCP
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        authorization-mode: "AlwaysAllow"
