---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: istio
  namespace: istio-system
spec:
  replicas: 1
  podMetadata:
    labels:
      app.kubernetes.io/name: prometheus-istio

  # TODO: Configure DNS and ingress to be able to connect
  externalUrl: http://localhost
  routePrefix: "/"

  serviceAccountName: prometheus-istio

  retention: "10d"
  # portName: web

  serviceMonitorNamespaceSelector: {} # auto discovers all service monitors across all namespaces
  serviceMonitorSelector: {} # auto discovers all service monitors in namespaces configured one line above
  ruleNamespaceSelector: {} # auto discovers all prometheus rules across all namespaces
  ruleSelector: {} # auto discovers all prometheus rules in namespaces configured one line above

  additionalScrapeConfigs:
    key: istio-scrape-configs.yaml
    name: istio-scrape-configs

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus-istio
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-istio
  namespace: istio-system
  labels:
    app.kubernetes.io/name: prometheus-istio
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus-istio
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prometheus-istio
  namespace: istio-system
  labels:
    app.kubernetes.io/name: prometheus-istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-istio
